FROM node:16-alpine

WORKDIR '/app'

# USER node

COPY --chown=node:node package.json .

RUN npm install

# RUN chmod -R 777 /app/node_modules/

COPY --chown=node:node . .

 USER node

CMD [ "npm", "run", "start" ]